"""Exact generalized Kaprekar arithmetic and dynamics."""

from .core import (
    ComputationLimitError,
    Spectrum,
    digit_multiset_count,
    digits_base,
    enumerate_spectra,
    kaprekar_map,
    kaprekar_spectrum_from_digits,
    lambda_bn,
    number_from_digits,
    representative_from_spectrum,
    sigma_of_number,
    spectrum_count,
    spectrum_of_number,
    validate_base_and_digits,
    validate_number,
    validate_spectrum,
)
from .dynamics import (
    AttractorAnalysis,
    EntropyPoint,
    FunctionalGraphAnalysis,
    StateAnalysis,
    analyze_functional_graph,
    decimal_fixed_spectra,
    fixed_spectra,
    raw_spectrum_weights,
    reduced_map,
    uniform_entropy_trajectory,
)
from .logits import (
    GapSimplex,
    MarginDiagnostic,
    TailMassBounds,
    conditional_accepted_distribution,
    gap_simplex,
    reconstruct_sorted_logits,
    relaxed_margin_diagnostic,
    tail_mass_bounds,
)
from .selective import (
    SelectiveRiskCalibration,
    apply_abstention,
    calibrate_selective_risk,
    clopper_pearson_upper,
)
from .verification import (
    CaseVerification,
    VerificationReport,
    verify_case,
    verify_ranges,
)


__version__ = "0.1.0"

__all__ = [
    "AttractorAnalysis",
    "CaseVerification",
    "ComputationLimitError",
    "EntropyPoint",
    "FunctionalGraphAnalysis",
    "GapSimplex",
    "MarginDiagnostic",
    "SelectiveRiskCalibration",
    "Spectrum",
    "StateAnalysis",
    "TailMassBounds",
    "VerificationReport",
    "analyze_functional_graph",
    "apply_abstention",
    "calibrate_selective_risk",
    "clopper_pearson_upper",
    "conditional_accepted_distribution",
    "decimal_fixed_spectra",
    "digit_multiset_count",
    "digits_base",
    "enumerate_spectra",
    "fixed_spectra",
    "gap_simplex",
    "kaprekar_map",
    "kaprekar_spectrum_from_digits",
    "lambda_bn",
    "number_from_digits",
    "raw_spectrum_weights",
    "reconstruct_sorted_logits",
    "reduced_map",
    "relaxed_margin_diagnostic",
    "representative_from_spectrum",
    "sigma_of_number",
    "spectrum_count",
    "spectrum_of_number",
    "tail_mass_bounds",
    "uniform_entropy_trajectory",
    "validate_base_and_digits",
    "validate_number",
    "validate_spectrum",
    "verify_case",
    "verify_ranges",
]
